DROP DATABASE IF EXISTS hvl_ftw;
CREATE DATABASE hvl_ftw;
USE hvl_ftw;

DROP TABLE IF EXISTS faculty;
CREATE TABLE faculty (
  FCODE VARCHAR(10) NOT NULL,
  FNAME VARCHAR(10) NOT NULL,
  FADDR VARCHAR(25),
  FPHONE INT,
  PRIMARY KEY (FCODE)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS student;
CREATE TABLE student (
  SNR INT UNSIGNED NOT NULL AUTO_INCREMENT,
  SNAME VARCHAR(25) NOT NULL,
  NIN INT UNSIGNED NOT NULL,
  HADDR VARCHAR(25),
  SADDR VARCHAR(25) NOT NULL,
  SPHONE INT,
  GENDER ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL ,
  BDATE DATE NOT NULL,
  SYEAR YEAR NOT NULL,
  FCODE VARCHAR(10),
  PRIMARY KEY (SNR),
  FOREIGN KEY (FCODE) REFERENCES faculty(FCODE)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS courseeparticipants;
CREATE TABLE courseeparticipants (
  SNR INT UNSIGNED NOT NULL,
  CCODE VARCHAR(10) NOT NULL,
  CYEAR YEAR NOT NULL,
  GRADE CHAR(1),
  PRIMARY KEY (SNR, CCODE, CYEAR),
  FOREIGN KEY (SNR) REFERENCES student(SNR)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS studyprogram;
CREATE TABLE studyprogram (
  SPROG_ID VARCHAR(10) NOT NULL,
  SPROG_NAME VARCHAR(25) NOT NULL,
  CLEVEL VARCHAR(25),
  FCODE VARCHAR(10),
  PRIMARY KEY (SPROG_ID),
  FOREIGN KEY (FCODE) REFERENCES faculty(FCODE)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS course;
CREATE TABLE course (
  CCODE VARCHAR(10) NOT NULL,
  CNAME VARCHAR(25) NOT NULL,
  CLEVEL VARCHAR(25) NOT NULL,
  SPROG_ID VARCHAR(10),
  PRIMARY KEY (CCODE),
  FOREIGN KEY (SPROG_ID) REFERENCES studyprogram(SPROG_ID)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS courseschedule;
CREATE TABLE courseschedule (
  CCODE VARCHAR(10) NOT NULL,
  CYEAR YEAR NOT NULL,
  TEACHER VARCHAR(25) NOT NULL,
  CHOURS FLOAT,
  PRIMARY KEY (CCODE, CYEAR),
  FOREIGN KEY (CCODE) REFERENCES course(CCODE) 
) ENGINE=InnoDB;
